name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 23 (Adoptium)
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Set up Maven
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip
        unzip apache-maven-3.9.9-bin.zip
        mv apache-maven-3.9.9 /usr/local/apache-maven
        export PATH=/usr/local/apache-maven/bin:$PATH
        mvn -v

    - name: Build and test with Maven
      run: mvn clean install
